name = "rustwasm-fullstack-app"
main = "build/worker/shim.mjs"
#pages_build_output_dir = "./frontend/public" # frontendディレクトリ内の./publicディレクトリ
compatibility_date = "2025-06-16"

[build]
command = "cargo install -q worker-build && worker-build --release"