# rustwasm-fullstack-app/wrangler.toml (Pages専用)

name = "my-stock-frontend-pages"

#[pages]
# ビルド出力ディレクトリへのパスを指定
pages_build_output_dir = "./frontend/public" # ⭐️ ビルド後のHTMLがあるディレクトリを指定 (例)

# Pagesのビルド設定
#[pages.build]
# PagesがGitHubからリポジトリをクローンした後、まずfrontendディレクトリに移動
#command = "npm install && npm run build" # frontend/package.jsonがあるなら
#cwd = "frontend" # commandを実行するディレクトリ (もし必要なら)